package src.CodingNinja;

public class CheckPalindrome {
    public static boolean isPalindrome(String str) {
        int n = str.length();
        boolean check = false;
        for(int i=0; i<n/2; i++) {
            if(str.charAt(i) == str.charAt(n-i-1))
                check = true;
            else{
                return false;
            }
        }
        return check;
    }

    public static void main(String[] args) {
        System.out.println("racecar: "+isPalindrome("racecar"));
        System.out.println("2nd: "+isPalindrome("dbiidlacpuxpzgeqsxwaaknfsfdcsfvtjikrwpmiedieefybtekoxpttullqyjwpmmeitfqupjcmlswuaiayzllzpwukkilupobltabggcrlcpeagiyupjsxisadfjguqiusqwjsviyimvqeoclkeuuewcnnqfltkyfjvxttrlfaazetmpmyfkskeflsgcioxfpkwsorwsisdzepwudevbtbnvuhkesznoingkuwbvppkucqtzisjmvgtpyheslkfwaqyfljxmsosryctntaiwmrdgxfxvokowafxslovjzqagvkhjyvwfoghkhdewhpquujwcsqmxsuiohvkfosglfwinsjcfptschlofnudmuzjdcsjkhiiryiyrabiyozybztucpnfctbfusxphmtyvtsixeplxmhwulvuvytcfdmtsvfdgdnpfbihpgywiswpfrulffchgcgfjvkorvfyfguufuczvbauxfurzoopicsmkskihmfhojfkomdxtplkjrbypjvhdfrxvvmkvyhrfylpqepvztwmfnpvoabigvtwtkebsuamyauqsvtqolzuaidhhdebaiokvjoaqkzpejxkduqhsbpsbtgsyddnraojngaimhswoyiidlllddifgcwazclnygoqopdupoxwofwbvjhnermdnotmslgojoflrmmpvnyoztzckmzgwdudxjzmmhwovgfbqdfjpftidepgzievelwerzlzpwystuafywkpjjvfpkrkutbmnjojugwmdgklbkwyqojbsozzkzldrhxkfmzlpyqcdhsaywttorrdjzhnktgnxsciaapqkepszjxqpisunkxwoibtswydpvuxhxytxobxkptbofygpydvtsmgnujecyuonzjudnzivwcelvtulptvfzmrxqmjeuwcakijlshjiivddyljkxjflhblmklrvcqszawfnrbjamcbymvbkdwxaayzjeafjcratxdtmuseqaooaldipqmxlilkdgukguxpemzujvyijkptbjrygkfdinsrhyveobhtitznwcyqfyjjiwmdxkcmfhoicmpinkbacbhouhincslzlucmsmtbtqlaaengltzjncyloikfdgncbitrhyzxveombmaoqnktwdqzggruvzycvwurxeidcerbkrmrlwciwapwjdzbzhkejfigtucrcccystrinwualuifpjzelvrecepgduipfgcqdhxlnfeojtznfglibcylhrxuzaosbapscqecvhwyhogjgcdmvgpxiuynznpoggyecfmalczpqxaayfapbbqrqevziphyebrhnhxdcotsarzocvcknqpcesgosqofmcyvqqoevzccqcvownvyigzcasdhtotqnduyulodsycslajodbakdtpkhjpawzaiidpjxzaamxonhhxsuqsiladsinemqvwqpcpluegvobjwfjsvztqxglfxpalqlojvayzahpdgbhffitaorcvmlejlmyobpdlzsfnuzypwzpopksxwjliainazebxsxntlsvhcjdakodogyckczlcqgqzssdbijilulyechwlxngmtjmnsmtetcbgjhmkarnptqswfkqmnjyjsvglcbbvoowbrzvzgxghbtyszezbjfebvuykfayryrqgmikanebcnwqysqsikfqusfocxaykezpgdmebufkxymychptyvgnwyloodxpmqzgnjfkfquloqsmfvclqtcbapvosomtmhgoxhloguzxluaytqhoauammyjhmpoocqovjzsokhawomxggoymgtlommdhxjpcacojadunqqopmbwkhuoyukrmbpxflkevvybdixrmcznpkbbxrwodzkfgijqysvztsjrwxhnzwfpqmwigwbvnffhrxueizilhvspykiorpglmsaorukdnyoetasdnknnzobeszesgzdkfkwrzdgbvbcbfnijksdqxujwkuegalgunlstghksfpzgpmvzgrxcnffjingthhajlrmmodaixqwshvgdrnibvxayididhjgceeujpipbpsjicihdwdpoxztyaxzdyewcmpfqcotgncjspjxphzisbdzgmhywcetsmodyhzvqzwwpaozgemboizlwylhuyyvjmoswvmvytklwudyrfqxgmqmnlzamooflgdqrilegtkpnjntxgzgfpsfmteuytkzsipmhzgricbzgnvigfcfgadetvqbnyjopdpkkycvigwgkqtqcobhvdywtwtmoltvpltdqlpxwxhlisnbmfobkyaocqqitiqstpmppxvfgvizbtiblfocehpxppxavodbxrqxjjvswihuytibhsreqdbqfolhliojnincfzynedzxbgnaxshwysmmcuvijavglektwklrajhbcfotohxszfjgoleyhllftdnzzqjtxexlecrrcbdeyscemskdilfjblhdqhzgihvwausswsolsshtvjncxwvhviemwqwveqzhkusijmuulansewdilmpyxhuurazlfrfztvtqzinelgaqmfykjbtpvcssgendtggaegimpseiqwbajempdzdzepmnwrajpbvjdxdlgvjaevlxvrhqfykxvbegbruokggpdjummnrybbtwduawczzljawyogpzzeblpzewbpqtovfkarucxicmqttulxwdzdjorjdkgjypqlnftjvvuqzoqhcpfgobgcilfmbeuaqdwsfmagtzqmjtgmtzzjtkmcwfumpzqcisgmejfanlgakrdjcdnovpwxydvpijwawbcxrqsztgemyaoslvkdsblxkcpzphuabxtunsdtfjhzqzlwbsbihkbcreolptglzwelowioqrugpjudlqabkbeefqjjpsmbojcrripqunfdalzmljundszkohvmurswtkduajsovonzldoojlfobjqizooptkyokhtvhrlsaqfcokhwxnoynbpfi"));
    }
}
